#!/bin/bash

lines_count=0
files_count=0
width=24

function print_align {
	str=$(printf "%-50s%s" $1 $2) 
	echo "$str"
}

function count_file_lines {
	local lines
	files_count=$[ $files_count + 1]
	lines=`sed '/^$/d' $1 | wc -l`
	print_align $1 $lines
	return $lines
}

function count_dir_lines {
	local lines=0
	for file_or_dir in `ls $1`
	do
		file_or_dir=$1"/"$file_or_dir
		if [ -d $file_or_dir ]
		then
			count_dir_lines $file_or_dir
		else
			count_file_lines $file_or_dir
		fi
		lines_count=$[ $lines_count + $? ]
		lines=$[ $lines + 1 ]
	done
	return $lines
}

count_dir_lines "."
echo
echo "files_count: " $files_count
echo "lines_count: " $lines_count